"""create_core_tables

Revision ID: 99cb04a2f48a
Revises: 
Create Date: 2026-09-03 11:30:02.910602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99cb04a2f48a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('cultural_dietary_profile', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('waking_time', sa.Time(), nullable=False),
    sa.Column('breakfast_time', sa.Time(), nullable=False),
    sa.Column('lunch_time', sa.Time(), nullable=False),
    sa.Column('dinner_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('prescriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('raw_image_url', sa.String(length=1024), nullable=False),
    sa.Column('doctor_name', sa.String(length=255), nullable=True),
    sa.Column('doctor_specialty', sa.String(length=255), nullable=True),
    sa.Column('date_prescribed', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARSED', 'VERIFIED', 'RECONCILED', name='prescriptionstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_user_id'), ['user_id'], unique=False)

    op.create_table('medication_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prescription_id', sa.Uuid(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('generic_molecule', sa.String(length=255), nullable=True),
    sa.Column('form', sa.String(length=64), nullable=False),
    sa.Column('strength', sa.String(length=64), nullable=False),
    sa.Column('frequency', sa.Enum('OD', 'BD', 'TID', 'QID', 'SOS', name='medicationfrequency', native_enum=False), nullable=False),
    sa.Column('timing_relation', sa.Enum('AC', 'PC', 'WITH_FOOD', name='timingrelation', native_enum=False), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('remaining_pills', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_items_brand_name'), ['brand_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_items_generic_molecule'), ['generic_molecule'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_items_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_items_prescription_id'), ['prescription_id'], unique=False)

    op.create_table('safety_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('medication_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sa.Enum('FOOD_INTERACTION', 'CUMULATIVE_TOXICITY', 'FASTING_CONFLICT', 'DUPLICATE_MOLECULE', name='safetyalerttype', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'MODERATE', 'CRITICAL', name='alertseverity', native_enum=False), nullable=False),
    sa.Column('advisory_text', sa.Text(), nullable=False),
    sa.Column('localized_advisory', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medication_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safety_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_alerts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_alerts_medication_id'), ['medication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('schedule_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('medication_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'TAKEN', 'SNOOZED', 'SKIPPED', name='schedulestatus', native_enum=False), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medication_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_items_medication_id'), ['medication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_items_scheduled_timestamp'), ['scheduled_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_items_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_items_status'))
        batch_op.drop_index(batch_op.f('ix_schedule_items_scheduled_timestamp'))
        batch_op.drop_index(batch_op.f('ix_schedule_items_medication_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_items_id'))

    op.drop_table('schedule_items')
    with op.batch_alter_table('safety_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_safety_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_safety_alerts_medication_id'))
        batch_op.drop_index(batch_op.f('ix_safety_alerts_id'))
        batch_op.drop_index(batch_op.f('ix_safety_alerts_alert_type'))

    op.drop_table('safety_alerts')
    with op.batch_alter_table('medication_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_items_prescription_id'))
        batch_op.drop_index(batch_op.f('ix_medication_items_is_active'))
        batch_op.drop_index(batch_op.f('ix_medication_items_id'))
        batch_op.drop_index(batch_op.f('ix_medication_items_generic_molecule'))
        batch_op.drop_index(batch_op.f('ix_medication_items_brand_name'))

    op.drop_table('medication_items')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_status'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_id'))

    op.drop_table('prescriptions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
